(function(){
  'use strict';
  const Core=globalThis.HeunjeokCore;const History=globalThis.HeunjeokHistory;const Photos=globalThis.HeunjeokPhotos;const $=selector=>document.querySelector(selector);const $$=selector=>[...document.querySelectorAll(selector)];
  const keys={tone:'heunjeok-naver-tone',pkg:'heunjeok-naver-package',workspace:'heunjeok-naver-workspace',blog:'heunjeok-naver-blog-profile',versions:'heunjeok-naver-versions'};
  let state={tone:null,topic:'',experienceAnswers:{},pkg:null,blogProfile:null,generatedInput:'',replySource:'',toastTimer:null,workspaceTimer:null,versionTimer:null,photoUrls:[],csrfToken:'',loggedIn:false,searchAdsEnabled:false,aiRequestId:0,toneRequestId:0,replyRequestId:0,trendRequestId:0,keywordRequestId:0};
  const els={blogUrl:$('#blogUrl'),connectBlog:$('#connectBlog'),disconnectBlog:$('#disconnectBlog'),blogConnectionStatus:$('#blogConnectionStatus'),openConnectedBlog:$('#openConnectedBlog'),dataInventory:$('#dataInventory'),refreshDataInventory:$('#refreshDataInventory'),exportLocalData:$('#exportLocalData'),deleteAllLocalData:$('#deleteAllLocalData'),category:$('#category'),topicList:$('#topicList'),customTopic:$('#customTopic'),useCustomTopic:$('#useCustomTopic'),selectedTopicStatus:$('#selectedTopicStatus'),toneSamples:$('#toneSamples'),toneCount:$('#toneCount'),toneError:$('#toneError'),avoidPhrases:$('#avoidPhrases'),saveTone:$('#saveTone'),deleteTone:$('#deleteTone'),toneProfile:$('#toneProfile'),postType:$('#postType'),experienceFields:$('#experienceFields'),moreExperience:$('#moreExperience'),moreExperienceFields:$('#moreExperienceFields'),interviewProgress:$('#interviewProgress'),memo:$('#memo'),memoCount:$('#memoCount'),photoNotes:$('#photoNotes'),relationship:$('#relationship'),workspaceSaveState:$('#workspaceSaveState'),clearWorkspace:$('#clearWorkspace'),generate:$('#generate'),clearLocalData:$('#clearLocalData'),resultPanel:$('#resultPanel'),resultState:$('#resultState'),liveStatus:$('#liveStatus'),emptyResult:$('#emptyResult'),resultContent:$('#resultContent'),staleNotice:$('#staleNotice'),titleCandidates:$('#titleCandidates'),draft:$('#draft'),draftSaveState:$('#draftSaveState'),provenanceSummary:$('#provenanceSummary'),provenanceList:$('#provenanceList'),humanCheckState:$('#humanCheckState'),humanCheckList:$('#humanCheckList'),humanGoodSignals:$('#humanGoodSignals'),photoPlan:$('#photoPlan'),hashtags:$('#hashtags'),specificityLevel:$('#specificityLevel'),specificitySignals:$('#specificitySignals'),experienceBoost:$('#experienceBoost'),applyExperience:$('#applyExperience'),checkProgress:$('#checkProgress'),copyTitle:$('#copyTitle'),copyBody:$('#copyBody'),copyTags:$('#copyTags'),copyAll:$('#copyAll'),copyLockReason:$('#copyLockReason'),commentInput:$('#commentInput'),makeReplies:$('#makeReplies'),replyArea:$('#replyArea'),replyList:$('#replyList'),toast:$('#toast')};
  Object.assign(els,{relationshipNotice:$('#relationshipNotice'),trustPanel:$('#trustPanel'),trustSummary:$('#trustSummary'),mobilePreview:$('#mobilePreview')});
  els.toneSourceUrl=document.createElement('input');els.approveToneSource=document.createElement('input');
  for(const name of ['blogUrl','connectBlog','disconnectBlog','blogConnectionStatus','openConnectedBlog'])els[name]=document.createElement(name==='openConnectedBlog'?'a':name==='blogConnectionStatus'?'span':name==='blogUrl'?'input':'button');
  els.naverLogin=document.createElement('button');els.naverLogout=document.createElement('button');els.naverLoginStatus=document.createElement('span');
  for(const name of ['loadTrend','trendResult','trendMeta','trendPoints','loadKeywords','keywordStatus','keywordResult','keywordMeta','keywordList'])els[name]=document.createElement(name.includes('Points')||name.includes('List')?'ul':name.startsWith('load')?'button':'div');
  els.draftVersion=$('#draftVersion');els.restoreVersion=$('#restoreVersion');
  els.photoFiles=$('#photoFiles');els.clearPhotos=$('#clearPhotos');els.photoVaultList=$('#photoVaultList');els.photoVaultStatus=$('#photoVaultStatus');
  function safeRead(key){try{return localStorage.getItem(key)}catch{return null}}
  function safeWrite(key,value){try{localStorage.setItem(key,value);return true}catch{return false}}
  function safeRemove(key){try{localStorage.removeItem(key);return true}catch{return false}}
  async function renderPhotoVault(){state.photoUrls.forEach(URL.revokeObjectURL);state.photoUrls=[];els.photoVaultList.innerHTML='';try{const photos=await Photos.listPhotos();photos.forEach((photo,index)=>{const item=document.createElement('li');const image=document.createElement('img');const url=URL.createObjectURL(photo.blob);state.photoUrls.push(url);image.src=url;image.alt=(index+1)+'번째 취재 사진';const button=document.createElement('button');button.type='button';button.className='text-button';button.textContent='삭제';button.setAttribute('aria-label',(index+1)+'번째 취재 사진 삭제');button.addEventListener('click',async()=>{if(!confirm('이 기기에서 이 사진을 삭제할까요?'))return;await Photos.removePhoto(photo.id);renderPhotoVault()});item.append(image,button);els.photoVaultList.append(item)});els.photoVaultStatus.textContent=photos.length+'장 저장됨 · 축소·메타데이터 제거 사본 · 서버 전송 없음'}catch{els.photoVaultStatus.textContent='이 브라우저에서는 사진 취재함을 사용할 수 없어요.'}}
  async function addPhotoFiles(){const files=[...els.photoFiles.files];els.photoFiles.value='';for(const file of files){try{await Photos.addPhoto(file)}catch(error){toast(error.message);break}}await renderPhotoVault();workspaceChanged()}
  async function loadTrend(){const keyword=String(state.topic||els.customTopic.value||'').trim();if(keyword.length<2){toast('먼저 확인할 주제를 골라주세요.');return}if(!state.loggedIn||!state.csrfToken){toast('공식 데이터를 확인하려면 네이버 로그인이 필요해요.');return}const requestId=++state.trendRequestId;els.loadTrend.disabled=true;els.loadTrend.textContent='확인 중';try{const response=await fetch('/api/v1/naver/trend',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json','X-CSRF-Token':state.csrfToken},body:JSON.stringify({keyword})});const payload=await response.json();if(!response.ok||!payload.trend)throw new Error(payload.error||'trend_failed');if(requestId!==state.trendRequestId||keyword!==String(state.topic||els.customTopic.value||'').trim())return;const trend=payload.trend;els.trendPoints.innerHTML='';trend.points.slice(-12).forEach(point=>{const item=document.createElement('li');const bar=document.createElement('span');bar.style.height=Math.max(4,Math.min(100,Number(point.ratio)))+'px';const value=document.createElement('b');value.textContent=Number(point.ratio).toFixed(1);const date=document.createElement('small');date.textContent=String(point.period).slice(5);item.append(bar,value,date);els.trendPoints.append(item)});els.trendMeta.textContent='NAVER DataLab · '+trend.startDate+'~'+trend.endDate+' · 주간 상대값 · '+(trend.cached?'캐시 사용 · ':'')+'조회 '+new Date(trend.fetchedAt).toLocaleString('ko-KR');els.trendResult.hidden=false;setLive('실제 검색 횟수가 아닌 네이버 검색 관심도 상대 추세를 불러왔어요.')}catch{els.trendResult.hidden=false;els.trendMeta.textContent='현재 공식 데이터를 불러올 수 없어요. 추정값으로 대신 표시하지 않습니다.';els.trendPoints.innerHTML=''}finally{if(requestId===state.trendRequestId){els.loadTrend.disabled=false;els.loadTrend.textContent='상대 추세 확인'}}}
  async function refreshSearchAdsStatus(){if(location.protocol==='file:'||!state.csrfToken)return;try{const response=await fetch('/api/v1/naver/searchads/status',{credentials:'same-origin',headers:{accept:'application/json'}});const payload=await response.json();state.searchAdsEnabled=Boolean(response.ok&&payload.enabled);els.loadKeywords.hidden=!state.searchAdsEnabled;els.keywordStatus.textContent=state.searchAdsEnabled?'네이버 검색광고 API가 제공하는 월간 PC·모바일 검색수와 경쟁 참고값입니다.':'현재 배포에서는 제공하지 않습니다. 운영자의 약관 확인과 서버 설정 후에만 켜집니다.'}catch{state.searchAdsEnabled=false;els.loadKeywords.hidden=true;els.keywordStatus.textContent='현재 기능 상태를 확인할 수 없습니다.'}}
  function monthlyCountText(value){if(!value||typeof value.display!=='string')return'정보 없음';return value.display==='<10'?'10회 미만':Number(value.display).toLocaleString('ko-KR')+'회'}
  async function loadKeywords(){const keyword=String(state.topic||els.customTopic.value||'').trim();if(keyword.length<2){toast('먼저 확인할 주제를 골라주세요.');return}if(!state.searchAdsEnabled){toast('현재 배포에서는 월간 검색 참고값을 제공하지 않아요.');return}if(!state.loggedIn||!state.csrfToken){toast('공식 데이터를 확인하려면 네이버 로그인이 필요해요.');return}const requestId=++state.keywordRequestId;els.loadKeywords.disabled=true;els.loadKeywords.textContent='확인 중';try{const response=await fetch('/api/v1/naver/searchads/keywords',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json','X-CSRF-Token':state.csrfToken,accept:'application/json'},body:JSON.stringify({keyword})});const payload=await response.json();if(!response.ok||!payload.result||!Array.isArray(payload.result.keywords))throw new Error(payload.error||'keywords_failed');if(requestId!==state.keywordRequestId||keyword!==String(state.topic||els.customTopic.value||'').trim())return;els.keywordList.innerHTML='';payload.result.keywords.forEach(row=>{const item=document.createElement('li');const name=document.createElement('strong');const values=document.createElement('span');name.textContent=row.keyword;values.textContent=`PC ${monthlyCountText(row.monthlyPc)} · 모바일 ${monthlyCountText(row.monthlyMobile)} · 경쟁 ${row.competition}`;item.append(name,values);els.keywordList.append(item)});els.keywordMeta.textContent='NAVER Search Ads · 월간 검색수 참고값 · '+(payload.result.cached?'캐시 사용 · ':'')+'조회 '+new Date(payload.result.fetchedAt).toLocaleString('ko-KR');els.keywordResult.hidden=false;setLive('네이버가 제공한 월간 검색 참고값을 불러왔어요. CPC나 노출 예상값은 만들지 않았어요.')}catch{els.keywordResult.hidden=false;els.keywordList.innerHTML='';els.keywordMeta.textContent='현재 공식 데이터를 불러올 수 없어요. 임의의 숫자로 대신 표시하지 않습니다.'}finally{if(requestId===state.keywordRequestId){els.loadKeywords.disabled=false;els.loadKeywords.textContent='연관 검색어 확인'}}}
  function renderBlogConnection(){const profile=state.blogProfile;els.blogUrl.removeAttribute('aria-invalid');if(!profile){els.blogConnectionStatus.textContent='연결된 블로그 없음';els.openConnectedBlog.hidden=true;els.openConnectedBlog.removeAttribute('href');els.disconnectBlog.hidden=true;return}els.blogUrl.value=profile.url;els.blogConnectionStatus.textContent=`연결됨 · ${profile.blogId}`;els.openConnectedBlog.href=profile.url;els.openConnectedBlog.hidden=false;els.disconnectBlog.hidden=false}
  function connectBlog(){const normalized=Core.normalizeNaverBlogUrl(els.blogUrl.value);if(!normalized){els.blogUrl.setAttribute('aria-invalid','true');els.blogConnectionStatus.textContent='공식 네이버 블로그 주소를 확인해 주세요.';els.blogUrl.focus();toast('https://blog.naver.com/블로그ID 형식으로 입력해 주세요.');return}const profile={version:1,blogId:normalized.blogId,url:normalized.url,connectedAt:new Date().toISOString()};if(!safeWrite(keys.blog,JSON.stringify(profile))){els.blogConnectionStatus.textContent='브라우저 저장이 차단되어 연결하지 못했어요.';toast('브라우저 저장 권한을 확인해 주세요.');return}state.blogProfile=profile;renderBlogConnection();toast('블로그 주소를 이 브라우저에 연결했어요.')}
  function disconnectBlog(){if(!state.blogProfile){toast('연결된 블로그가 없어요.');return}if(!confirm('이 브라우저에서 블로그 주소 연결을 해제할까요? 초안과 말투 카드는 남아 있습니다.'))return;safeRemove(keys.blog);state.blogProfile=null;els.blogUrl.value='';renderBlogConnection();toast('블로그 주소 연결을 해제했어요.')}
  function restoreBlogConnection(){try{const raw=safeRead(keys.blog);if(!raw){renderBlogConnection();return}const saved=JSON.parse(raw);const normalized=saved&&saved.version===1?Core.normalizeNaverBlogUrl(saved.url):null;if(!normalized||normalized.blogId!==saved.blogId){safeRemove(keys.blog);state.blogProfile=null}else state.blogProfile={version:1,blogId:normalized.blogId,url:normalized.url,connectedAt:String(saved.connectedAt||'')};renderBlogConnection()}catch{safeRemove(keys.blog);state.blogProfile=null;renderBlogConnection()}}
  function renderLogin(loggedIn,unavailable=false){state.loggedIn=Boolean(loggedIn);els.naverLoginStatus.textContent=unavailable?'서버 연결 후 로그인 가능':loggedIn?'네이버 로그인됨':'네이버 로그인 안 됨';els.naverLogin.hidden=loggedIn||unavailable;els.naverLogout.hidden=!loggedIn}
  async function ensureSession(){if(location.protocol==='file:')throw new Error('server_required');const response=await fetch('/api/v1/session',{credentials:'same-origin',headers:{accept:'application/json'}});if(!response.ok)throw new Error('session_failed');const body=await response.json();state.csrfToken=body.csrfToken;return body}
  async function refreshLogin(){try{await ensureSession();const response=await fetch('/api/v1/auth/status',{credentials:'same-origin',headers:{accept:'application/json'}});if(!response.ok)throw new Error('status_failed');renderLogin(Boolean((await response.json()).loggedIn));await refreshSearchAdsStatus()}catch{state.csrfToken='';renderLogin(false,true)}}
  async function startNaverLogin(){els.naverLogin.disabled=true;try{await ensureSession();const response=await fetch('/api/v1/auth/naver/start',{credentials:'same-origin',headers:{accept:'application/json'}});const body=await response.json();if(!response.ok||!/^https:\/\/nid\.naver\.com\/oauth2\.0\/authorize\?/.test(body.authorizationUrl||''))throw new Error('start_failed');location.assign(body.authorizationUrl)}catch{els.naverLogin.disabled=false;toast('서버의 네이버 로그인 설정을 확인해 주세요.')}}
  async function logoutNaver(){if(!confirm('네이버 로그인을 종료할까요? 브라우저에 저장된 초안과 블로그 주소는 남습니다.'))return;try{if(!state.csrfToken)await ensureSession();const response=await fetch('/api/v1/session',{method:'DELETE',credentials:'same-origin',headers:{'X-CSRF-Token':state.csrfToken}});if(!response.ok)throw new Error('logout_failed');state.csrfToken='';renderLogin(false);await ensureSession();toast('네이버 로그인을 종료했어요.')}catch{toast('로그아웃하지 못했어요. 다시 시도해 주세요.')}}
  const dataLabels={workspace:'경험 입력',tone:'말투 카드',pkg:'초안',versions:'본문 버전'};
  function renderDataInventory(){els.dataInventory.innerHTML='';Object.entries(dataLabels).forEach(([name,label])=>{const raw=safeRead(keys[name]);const item=document.createElement('li');const info=document.createElement('div');const title=document.createElement('strong');const detail=document.createElement('span');title.textContent=label;detail.textContent=raw?`저장됨 · 약 ${new Blob([raw]).size.toLocaleString('ko-KR')}바이트`:'저장된 내용 없음';info.append(title,detail);const button=document.createElement('button');button.type='button';button.className='text-button';button.textContent='삭제';button.disabled=!raw;button.addEventListener('click',()=>{if(confirm(`${label}만 삭제할까요?`)){safeRemove(keys[name]);location.reload()}});item.append(info,button);els.dataInventory.append(item)})}
  function exportLocalData(){const data={format:'heunjeok-local-backup',version:1,exportedAt:new Date().toISOString(),data:{}};Object.keys(dataLabels).forEach(name=>{const raw=safeRead(keys[name]);if(raw)try{data.data[name]=JSON.parse(raw)}catch{}});const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`heunjeok-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.append(link);link.click();link.remove();URL.revokeObjectURL(link.href);toast('내 데이터 백업 파일을 만들었어요.')}
  function evidenceLength(value){return String(value||'').replace(/\s/g,'').length}
  function normalizedAnswers(){return Core.getInterviewFields(els.postType.value).reduce((result,field)=>{const value=String(state.experienceAnswers[field.key]||'').trim();if(value)result[field.key]=value;return result},{})}
  function workspaceSnapshot(){return{category:els.category.value,topic:state.topic,customTopic:els.customTopic.value.trim(),postType:els.postType.value,experienceAnswers:normalizedAnswers(),memo:els.memo.value.trim(),photoNotes:els.photoNotes.value.trim(),relationship:els.relationship.value,savedAt:new Date().toISOString()}}
  function renderRelationshipNotice(){const required=Core.requiredDisclosure(els.relationship.value);els.relationshipNotice.textContent=required?`본문 첫 줄에 고정됩니다: ${required}`:'협찬이 없다면 고지 문구를 넣지 않습니다.';els.relationshipNotice.classList.toggle('is-required',Boolean(required))}
  function savedTime(value){try{return new Date(value).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})}catch{return''}}
  function saveWorkspace(){clearTimeout(state.workspaceTimer);state.workspaceTimer=null;const snapshot=workspaceSnapshot();const stored=safeWrite(keys.workspace,JSON.stringify(snapshot));const message=stored?`${savedTime(snapshot.savedAt)} 입력 자동 저장됨`:'브라우저 저장이 차단됐어요';if(els.workspaceSaveState.textContent!==message)els.workspaceSaveState.textContent=message}
  function queueWorkspaceSave(){clearTimeout(state.workspaceTimer);state.workspaceTimer=setTimeout(saveWorkspace,450)}
  function updateInterviewProgress(){const fields=Core.getInterviewFields(els.postType.value);const completed=field=>evidenceLength(state.experienceAnswers[field.key])>=5;const essential=fields.filter(field=>field.essential);const optional=fields.filter(field=>!field.essential);const essentialAnswered=essential.filter(completed).length;const optionalAnswered=optional.filter(completed).length;const essentialCharacters=essential.filter(completed).reduce((total,field)=>total+evidenceLength(state.experienceAnswers[field.key]),0);const answered=essentialAnswered+optionalAnswered;const characters=fields.filter(completed).reduce((total,field)=>total+evidenceLength(state.experienceAnswers[field.key]),0);const message=`핵심 ${essentialAnswered}/${essential.length} · 선택 ${optionalAnswered}/${optional.length}`;if(els.interviewProgress.textContent!==message)els.interviewProgress.textContent=message;els.interviewProgress.dataset.state=answered===fields.length?'complete':essentialAnswered===essential.length?'ready':'start';return{answered,total:fields.length,characters,essentialAnswered,essentialTotal:essential.length,essentialCharacters}}
  function renderInterviewFields(answers=state.experienceAnswers){
    const next={};let hasOptionalAnswer=false;els.experienceFields.innerHTML='';els.moreExperienceFields.innerHTML='';
    let essentialIndex=0;let optionalIndex=0;Core.getInterviewFields(els.postType.value).forEach(field=>{
      const wrapper=document.createElement('div');wrapper.className='experience-field';const label=document.createElement('label');const input=document.createElement('textarea');
      input.id=`experience-${field.key}`;input.rows=2;input.placeholder=field.placeholder;input.value=String(answers&&answers[field.key]||'');input.dataset.experienceKey=field.key;input.setAttribute('aria-describedby','interviewHelp workspaceHelp');
      const number=field.essential?++essentialIndex:++optionalIndex;label.htmlFor=input.id;label.textContent=`${field.essential?'핵심':'선택'} ${number}. ${field.label}`;if(input.value.trim())next[field.key]=input.value.trim();if(!field.essential&&input.value.trim())hasOptionalAnswer=true;
      input.addEventListener('input',()=>{const value=input.value.trim();if(value)state.experienceAnswers[field.key]=value;else delete state.experienceAnswers[field.key];updateInterviewProgress();workspaceChanged()});
      wrapper.append(label,input);(field.essential?els.experienceFields:els.moreExperienceFields).append(wrapper);
    });
    state.experienceAnswers=next;els.moreExperience.open=hasOptionalAnswer||Boolean(els.memo.value.trim()||els.photoNotes.value.trim());els.postType.dataset.active=els.postType.value;updateInterviewProgress();
  }
  function workspaceChanged(){markStale();queueWorkspaceSave();if(state.topic)setStep(3)}
  function toast(message){clearTimeout(state.toastTimer);els.toast.textContent=message;els.toast.classList.add('is-visible');state.toastTimer=setTimeout(()=>els.toast.classList.remove('is-visible'),2600)}
  function setLive(message){els.liveStatus.textContent='';requestAnimationFrame(()=>{els.liveStatus.textContent=message})}
  function setStep(step){$$('.steps li').forEach((item,index)=>{const current=index===step-1;item.classList.toggle('is-current',current);if(current)item.setAttribute('aria-current','step');else item.removeAttribute('aria-current')})}
  function showManualCopy(text){let panel=$('#manualCopyFallback');if(!panel){panel=document.createElement('section');panel.id='manualCopyFallback';panel.className='manual-copy-fallback';panel.setAttribute('role','alert');const title=document.createElement('strong');title.textContent='자동 복사가 막혔어요';const help=document.createElement('p');help.textContent='아래 내용을 길게 눌러 전체 선택한 뒤 복사해 주세요.';const field=document.createElement('textarea');field.rows=8;field.readOnly=true;field.setAttribute('aria-label','수동으로 복사할 내용');const actions=document.createElement('div');actions.className='action-row';const select=document.createElement('button');select.type='button';select.className='primary';select.textContent='전체 선택';select.addEventListener('click',()=>{field.focus();field.select();field.setSelectionRange(0,field.value.length)});const close=document.createElement('button');close.type='button';close.className='secondary';close.textContent='닫기';close.addEventListener('click',()=>panel.hidden=true);actions.append(select,close);panel.append(title,help,field,actions);document.body.append(panel)}const field=panel.querySelector('textarea');field.value=text;panel.hidden=false;field.focus();field.select();field.setSelectionRange(0,field.value.length)}
  async function copyText(text,label){try{if(navigator.clipboard&&navigator.clipboard.writeText)await navigator.clipboard.writeText(text);else{const field=document.createElement('textarea');field.value=text;field.style.position='fixed';field.style.opacity='0';document.body.append(field);field.select();let copied=false;try{copied=document.execCommand('copy')}finally{field.remove()}if(!copied)throw new Error('copy failed')}toast(`${label} 복사했어요. 다음은 네이버 글쓰기에서 붙여넣기입니다.`)}catch{showManualCopy(text);toast('자동 복사가 막혀 수동 복사창을 열었어요.')}}
  function renderTopics(){const topics=Core.getTopics(els.category.value);els.topicList.innerHTML='';topics.forEach(item=>{const button=document.createElement('button');button.type='button';button.className='topic-card';button.setAttribute('aria-pressed',String(item.title===state.topic));const title=document.createElement('strong');title.textContent=item.title;const reason=document.createElement('p');reason.textContent=item.reason;const tags=document.createElement('div');tags.className='topic-tags';['경험형 아이디어',item.intent].forEach(text=>{const tag=document.createElement('span');tag.textContent=text;tags.append(tag)});button.append(title,reason,tags);button.addEventListener('click',()=>selectTopic(item.title));els.topicList.append(button)})}
  function clearTrend(){state.trendRequestId+=1;state.keywordRequestId+=1;els.trendResult.hidden=true;els.trendPoints.innerHTML='';els.trendMeta.textContent='';els.keywordResult.hidden=true;els.keywordList.innerHTML='';els.keywordMeta.textContent=''}
  function selectTopic(topic){clearTrend();state.topic=topic;els.selectedTopicStatus.textContent=`선택한 주제: ${topic}`;renderTopics();workspaceChanged();setStep(3);const firstAnswer=els.experienceFields.querySelector('textarea');if(firstAnswer){firstAnswer.scrollIntoView({behavior:'smooth',block:'center'});firstAnswer.focus({preventScroll:true})}toast('주제를 골랐어요. 먼저 보이는 질문 세 개부터 답해보세요.')}
  function useCustomTopic(){const topic=els.customTopic.value.trim();if(topic.length<3){els.customTopic.focus();toast('주제를 3자 이상 적어주세요.');return}selectTopic(topic)}
  function renderTone(){if(!state.tone){els.toneProfile.innerHTML='<p>등록하지 않아도 됩니다. 이 경우 경험 답변의 문장을 그대로 살려 초안을 엮어요.</p>';return}els.toneProfile.innerHTML='';const wrap=document.createElement('div');wrap.className='tone-chips';const connectorText=Array.isArray(state.tone.connectors)&&state.tone.connectors.length?`자주 쓰는 말: ${state.tone.connectors.join(' · ')}`:'';const avoidText=Array.isArray(state.tone.avoidPhrases)&&state.tone.avoidPhrases.length?`피할 말: ${state.tone.avoidPhrases.join(' · ')}`:'';[state.tone.ending,state.tone.sentenceLength,state.tone.paragraphStyle,state.tone.emoji,connectorText,avoidText].filter(Boolean).forEach(text=>{const chip=document.createElement('span');chip.textContent=text;wrap.append(chip)});els.toneProfile.append(wrap)}
  async function requestAiTone(text,avoidPhrases,sourceReference,localSignature){if(!state.loggedIn||!state.csrfToken)return;const requestId=++state.toneRequestId;try{const response=await fetch('/api/v1/ai/tone',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json','X-CSRF-Token':state.csrfToken},body:JSON.stringify({text})});const payload=await response.json();if(!response.ok||!payload.result||requestId!==state.toneRequestId||JSON.stringify(state.tone)!==localSignature)return;state.tone={...payload.result,avoidPhrases,sourceReference,analyzedBy:'ai'};safeWrite(keys.tone,JSON.stringify(state.tone));renderTone();toast('AI가 원문을 저장하지 않고 말투 특징을 더 자세히 반영했어요.')}catch{}}
  function toneInputChanged(){const length=els.toneSamples.value.trim().length;els.toneCount.textContent=`${length}자`;els.saveTone.disabled=length<30;els.toneError.hidden=true;els.toneSamples.removeAttribute('aria-invalid')}
  function saveTone(){const text=els.toneSamples.value.trim();if(text.length<30){els.toneError.textContent='말투를 파악할 수 있도록 30자 이상 넣어주세요.';els.toneError.hidden=false;els.toneSamples.focus();return}const avoidPhrases=els.avoidPhrases.value.split(/[,\n]+/).map(value=>value.trim()).filter(value=>value.length>=2).slice(0,10);state.tone={...Core.analyzeTone(text),strength:document.getElementById('toneStrength')?.value||'weak',avoidPhrases,sourceReference:null};const localSignature=JSON.stringify(state.tone);const stored=safeWrite(keys.tone,localSignature);renderTone();els.toneSamples.value='';els.avoidPhrases.value='';toneInputChanged();toast(stored?'말투 카드만 저장했어요. 붙여넣은 원문은 저장하지 않았습니다.':'말투는 분석했지만 브라우저 저장이 차단됐어요.');workspaceChanged();setStep(3)}
  function deleteTone(){if(!state.tone){toast('삭제할 말투 카드가 없어요.');return}if(!confirm('저장된 말투 카드를 삭제할까요? 이 작업은 되돌릴 수 없습니다.'))return;state.tone=null;els.avoidPhrases.value='';safeRemove(keys.tone);renderTone();workspaceChanged();toast('말투 카드를 삭제했어요.')}
  function currentInput(){return JSON.stringify({category:els.category.value,topic:state.topic,postType:els.postType.value,experienceAnswers:normalizedAnswers(),memo:els.memo.value.trim(),photos:els.photoNotes.value.trim(),relationship:els.relationship.value,tone:state.tone})}
  function packageIsCurrent(pkg){return Boolean(pkg&&pkg.packageVersion===Core.PACKAGE_VERSION&&pkg.provenance&&Array.isArray(pkg.usedEvidence))}
  function markStale(){els.memoCount.textContent=`${els.memo.value.trim().length}자`;if(!state.pkg||!state.generatedInput)return;const stale=currentInput()!==state.generatedInput;els.staleNotice.textContent='경험 내용이 바뀌었어요. 다시 만들기 전에는 이전 결과를 복사할 수 없습니다.';els.staleNotice.hidden=!stale;if(stale){els.resultState.textContent='다시 만들기 필요';resetPublishChecks('입력 변경으로 다시 확인 필요');setCopyEnabled(false,'경험 내용이 바뀌어 초안을 다시 만들어야 복사할 수 있어요.')}else{if(els.resultState.textContent==='다시 만들기 필요')els.resultState.textContent=state.pkg.specificity.level==='보완용 뼈대'?'보완 권장':'검수 가능';setCopyEnabled(true);renderHumanAudit()}}
  function setCopyControl(button,enabled){button.disabled=false;button.setAttribute('aria-disabled',String(!enabled));if(enabled)button.removeAttribute('aria-describedby');else button.setAttribute('aria-describedby','copyLockReason')}
  function setCopyEnabled(enabled,reason=''){ $$('.copy-control').forEach(button=>setCopyControl(button,enabled));els.copyLockReason.textContent=enabled?'':reason||'현재 결과는 다시 확인해야 복사할 수 있어요.';if(!enabled)setLive(els.copyLockReason.textContent)}
  function copyControlReady(button){if(button.getAttribute('aria-disabled')!=='true')return true;toast(els.copyLockReason.textContent||'현재 결과는 복사할 수 없어요.');return false}
  function aiEvidence(answers,memo){const evidence={...answers};if(evidenceLength(memo)>=10)evidence.memo=memo;return evidence}
  function mergeAiDraft(base,draft){const paragraphs=draft.paragraphs.map(item=>item.text.trim()).filter(text=>text&&text!==base.disclosure);const body=[base.disclosure,...paragraphs].filter(Boolean).join('\n\n');const hashtags=draft.hashtags.map(value=>`#${String(value).replace(/^#+/,'').replace(/\s+/g,'').replace(/[^0-9A-Za-z가-힣_]/g,'')}`).filter(value=>value.length>1).slice(0,15);return{...base,titles:draft.titles,body,photoPlan:draft.photoPlan.length?draft.photoPlan:base.photoPlan,hashtags:hashtags.length?hashtags:base.hashtags,aiParagraphs:draft.paragraphs,provenance:{...base.provenance,aiGenerated:true,addedFacts:0}}}
  async function requestAiDraft(base,answers,memo,fingerprint){if(!state.loggedIn||!state.csrfToken){setLive('로컬 초안을 만들었어요. 네이버 로그인 후 AI로 더 자연스럽게 다듬을 수 있어요.');return}const requestId=++state.aiRequestId;const draftSnapshot=els.draft.value;els.generate.disabled=true;els.resultState.textContent='AI가 다듬는 중';setLive('입력한 근거만 사용해 AI가 문장을 다듬고 있어요.');try{const response=await fetch('/api/v1/ai/draft',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json','X-CSRF-Token':state.csrfToken,accept:'application/json'},body:JSON.stringify({topic:state.topic,postType:els.postType.value,memo,photoNotes:els.photoNotes.value.trim(),evidence:aiEvidence(answers,memo),tone:state.tone,relationship:els.relationship.value})});const payload=await response.json();if(!response.ok||!payload.draft)throw new Error(payload.error||'ai_failed');if(requestId!==state.aiRequestId||fingerprint!==currentInput())return;if(els.draft.value!==draftSnapshot){els.resultState.textContent='내 편집본 유지';setLive('AI 응답보다 내가 수정한 본문을 우선해 그대로 유지했어요.');return}state.pkg=mergeAiDraft(base,payload.draft);state.pkg.sourceFingerprint=fingerprint;renderPackage(state.pkg);savePackage();els.resultState.textContent='AI 초안 · 검수 필요';setLive('AI 초안을 만들었어요. 사실·가격·최신 정보는 발행 전에 확인해 주세요.')}catch{if(requestId===state.aiRequestId&&fingerprint===currentInput()){state.pkg=base;els.resultState.textContent='로컬 초안 · AI 연결 안 됨';setLive('AI 연결에 실패했지만 작성 내용과 로컬 초안은 안전하게 남아 있어요.');toast('AI 연결이 안 되어 로컬 초안을 유지했어요.')}}finally{if(requestId===state.aiRequestId)els.generate.disabled=false}}
  function generate(){const memo=els.memo.value.trim();const answers=normalizedAnswers();const progress=updateInterviewProgress();const memoStatus=Core.evaluateSpecificity(memo,{},els.postType.value);const memoReady=evidenceLength(memo)>=30&&memoStatus.signals.experience;if(!state.topic){els.selectedTopicStatus.textContent='먼저 주제를 하나 골라주세요.';els.selectedTopicStatus.scrollIntoView({behavior:'smooth',block:'center'});toast('먼저 주제를 골라주세요.');return false}if(progress.essentialAnswered<progress.essentialTotal&&!memoReady){const essentials=Core.getInterviewFields(els.postType.value).filter(field=>field.essential);const target=essentials.find(field=>evidenceLength(answers[field.key])<5);const field=target&&$(`#experience-${target.key}`);if(field)field.focus();else{els.moreExperience.open=true;els.memo.focus()}toast('핵심 질문 세 개를 각각 다섯 글자 이상 답하거나, 실제 경험 메모를 30자 이상 적어주세요.');return false}const local=Core.createPackage({topic:state.topic,memo,tone:state.tone,category:els.category.value,postType:els.postType.value,experienceFields:answers,photoNotes:els.photoNotes.value.trim(),relationship:els.relationship.value});state.pkg=local;state.generatedInput=currentInput();local.sourceFingerprint=state.generatedInput;renderPackage(local);savePackage();saveWorkspace();els.staleNotice.hidden=true;els.resultState.textContent=local.specificity.level==='보완용 뼈대'?'보완 권장':'검수 가능';setStep(4);setLive('내 답변을 중심으로 안전한 로컬 초안을 만들었어요.');requestAnimationFrame(()=>{els.resultPanel.scrollIntoView({behavior:'smooth',block:'start'});els.resultPanel.focus({preventScroll:true})});return true}
  function readVersions(){try{return History.normalizeVersions(JSON.parse(safeRead(keys.versions)||'[]'))}catch{return[]}}
  function renderVersions(){const versions=readVersions();els.draftVersion.innerHTML='<option value="">복구할 버전 선택</option>';versions.slice().reverse().forEach((version,reverseIndex)=>{const option=document.createElement('option');option.value=String(versions.length-1-reverseIndex);option.textContent=new Date(version.savedAt).toLocaleString('ko-KR')+' · '+version.reason+' · '+version.draft.replace(/\s+/g,' ').slice(0,24);els.draftVersion.append(option)});els.restoreVersion.disabled=true}
  function saveVersion(reason='편집'){if(!state.pkg)return false;const versions=History.addVersion(readVersions(),{draft:els.draft.value,topic:state.pkg.topic,savedAt:new Date().toISOString(),reason});const stored=safeWrite(keys.versions,JSON.stringify(versions));if(stored)renderVersions();return stored}
  function queueVersion(){clearTimeout(state.versionTimer);state.versionTimer=setTimeout(()=>{state.versionTimer=null;saveVersion('편집')},2000)}
  function restoreDraftVersion(){const versions=readVersions();const index=Number(els.draftVersion.value);if(!Number.isInteger(index)||!versions[index])return;if(!confirm('선택한 본문 버전으로 복구할까요? 현재 본문도 복구 목록에 먼저 보관합니다.'))return;saveVersion('복구 전');els.draft.value=versions[index].draft;state.pkg.draft=els.draft.value;savePackage();resetPublishChecks('버전 복구 후 다시 확인 필요');syncProvenanceState();renderHumanAudit();renderVersions();toast('선택한 본문 버전을 복구했어요.')}
  function savePackage(){if(!state.pkg)return false;const saved={...state.pkg,sourceFingerprint:state.generatedInput||state.pkg.sourceFingerprint||'',draft:els.draft.value};const stored=safeWrite(keys.pkg,JSON.stringify(saved));els.draftSaveState.textContent=stored?'자동 저장됨':'저장되지 않음';return stored}
  function resetPublishChecks(message=''){const checks=$$('input[name="publishCheck"]');checks.forEach(input=>input.checked=false);updateCheckProgress();if(message)els.checkProgress.textContent=`0/${checks.length} 확인 · ${message}`}
  function syncProvenanceState(){if(!state.pkg)return;els.provenanceSummary.classList.remove('is-edited','is-legacy');if(!packageIsCurrent(state.pkg)){els.provenanceSummary.textContent='이전 버전 초안이라 출처 보장을 확인할 수 없어요. 다시 만들어 주세요.';els.provenanceSummary.classList.add('is-legacy');return}if(els.draft.value!==state.pkg.body){els.provenanceSummary.textContent='본문을 수정했어요. 아래 내용은 생성 당시 출처이며, 수정한 문장은 따로 추적하지 않습니다.';els.provenanceSummary.classList.add('is-edited');return}const provenance=state.pkg.provenance;els.provenanceSummary.textContent=`초안 생성 때 내 답변 ${provenance.userEvidenceCount}개 사용 · 자동으로 추가한 사실 ${provenance.addedFacts}개`}
  function renderProvenance(pkg){const evidence=Array.isArray(pkg.usedEvidence)?pkg.usedEvidence:[];const provenance=pkg.provenance||{};els.provenanceList.innerHTML='';evidence.forEach(item=>{const row=document.createElement('li');row.textContent=`${item.heading}: ${String(item.text||'').replace(/\s+/g,' ').slice(0,90)}`;els.provenanceList.append(row)});if(provenance.connectivePhrases&&provenance.connectivePhrases.length){const row=document.createElement('li');row.className='connector-note';row.textContent=`문단 연결에 사용한 내 표현: ${provenance.connectivePhrases.join(' · ')}`;els.provenanceList.append(row)}if(provenance.disclosureAdded){const row=document.createElement('li');row.className='disclosure-note';row.textContent='선택한 광고·협찬 관계를 바탕으로 고지 문구를 첫 문장에 넣었어요.';els.provenanceList.append(row)}if(provenance.aiGenerated){const row=document.createElement('li');row.className='connector-note';row.textContent='AI는 입력한 근거를 문장으로 다듬는 데 사용했으며 새 사실을 허용하지 않았어요.';els.provenanceList.append(row);const checks=(pkg.aiParagraphs||[]).filter(item=>item.needsCurrentCheck).length;if(checks){const warning=document.createElement('li');warning.className='disclosure-note';warning.textContent=`최신 정보 확인이 필요한 문단 ${checks}개가 있어요. 발행 전에 가격·시간·정책을 확인해 주세요.`;els.provenanceList.append(warning)}}syncProvenanceState()}
  function renderHumanAudit(){if(!state.pkg)return;const audit=Core.auditHumanDraft(els.draft.value,state.pkg.topic,state.tone,{titles:state.pkg.titles,missingFields:state.pkg.missingFields,postType:state.pkg.postType});els.humanCheckList.innerHTML='';els.humanCheckState.textContent=audit.issues.length?`${audit.issues.length}곳 확인`:'선택한 패턴에서 경고 없음';if(!audit.issues.length){const item=document.createElement('li');item.className='is-clear';item.textContent='정해진 자동 문구·과장·편집 표시 패턴에서는 경고가 없어요.';els.humanCheckList.append(item)}else audit.issues.forEach(issue=>{const item=document.createElement('li');const title=document.createElement('strong');title.textContent=issue.title;const detail=document.createElement('span');detail.textContent=issue.detail;item.append(title,detail);if(issue.snippet){const snippet=document.createElement('code');snippet.textContent=issue.snippet;item.append(snippet)}els.humanCheckList.append(item)});els.humanGoodSignals.textContent=audit.goodSignals.length?`잘 살아 있는 부분: ${audit.goodSignals.join(' · ')}`:'구체적인 시간·수량·행동이나 아쉬운 점을 한 문장 더 넣으면 좋아요.';const stale=Boolean(state.generatedInput&&currentInput()!==state.generatedInput);const legacy=!packageIsCurrent(state.pkg);const bodyBlocked=audit.issues.some(issue=>issue.code==='placeholder');const titleBlocked=audit.issues.some(issue=>issue.code==='title-placeholder');if(legacy){setCopyEnabled(false,'이전 버전 초안은 현재 출처 기록으로 다시 만들어야 복사할 수 있어요.');return}if(stale){setCopyEnabled(false,'경험 내용이 바뀌어 초안을 다시 만들어야 복사할 수 있어요.');return}setCopyEnabled(true);const reasons=[];if(bodyBlocked){setCopyControl(els.copyBody,false);setCopyControl(els.copyAll,false);reasons.push('본문의 편집용 표시를 지우면 본문을 복사할 수 있어요.')}if(titleBlocked){setCopyControl(els.copyTitle,false);setCopyControl(els.copyAll,false);els.titleCandidates.querySelectorAll('.copy-control').forEach(button=>setCopyControl(button,false));reasons.push('제목의 편집용 표시를 지우면 제목을 복사할 수 있어요.')}els.copyLockReason.textContent=reasons.join(' ')}
  function renderPackage(pkg,restored=false){
    els.emptyResult.hidden=true;els.resultContent.hidden=false;els.titleCandidates.innerHTML='';
    pkg.titles.forEach((title,index)=>{const item=document.createElement('li');const text=document.createElement('span');text.textContent=title;const button=document.createElement('button');button.type='button';button.className='copy-control';button.textContent='복사';button.setAttribute('aria-label',`${index+1}번 제목 복사`);button.setAttribute('aria-describedby','copyLockReason');button.addEventListener('click',()=>copyControlReady(button)&&copyText(title,'제목을'));item.append(text,button);els.titleCandidates.append(item)});
    els.draft.value=Object.prototype.hasOwnProperty.call(pkg,'draft')?pkg.draft:pkg.body;els.photoPlan.innerHTML='';pkg.photoPlan.forEach(text=>{const item=document.createElement('li');item.textContent=text;els.photoPlan.append(item)});els.hashtags.textContent=pkg.hashtags.join(' ');
    renderProvenance(pkg);const completion=pkg.interviewCompletion;els.specificityLevel.textContent=completion?`${pkg.specificity.level} · ${completion.answered}/${completion.total}개 답변`:`입력 현황: ${pkg.specificity.level}`;
    els.specificitySignals.innerHTML='';const labels={numbers:['숫자가 포함된 답변이 있어요','가격·시간·수치가 필요한 글이라면 추가해 주세요'],experience:['경험 질문에 답했어요','실제로 한 행동이나 느낀 점을 추가해 주세요'],context:['언제·어디서 같은 맥락이 있어요','언제·어디서 있었던 일인지 추가해 주세요']};Object.entries(pkg.specificity.signals).forEach(([key,value])=>{const item=document.createElement('li');item.textContent=labels[key][value?0:1];els.specificitySignals.append(item)});
    if(Array.isArray(pkg.missingFields)&&pkg.missingFields.length){const item=document.createElement('li');item.textContent=`더 구체적으로 만들려면: ${pkg.missingFields.map(field=>field.heading).join(' · ')}`;els.specificitySignals.append(item)}
    resetPublishChecks();els.resultState.textContent=restored?'저장된 초안':pkg.specificity.level==='보완용 뼈대'?'보완 권장':'검수 가능';els.staleNotice.hidden=true;setCopyEnabled(true);renderHumanAudit()
  }
  function applyExperience(){const extra=els.experienceBoost.value.trim();if(!extra){els.experienceBoost.focus();toast('보강할 경험을 한 줄 적어주세요.');return}els.memo.value=`${els.memo.value.trim()}\n${extra}`.trim();els.experienceBoost.value='';workspaceChanged();if(generate())toast('경험을 반영해 다시 만들었어요.')}
  function draftChanged(){if(!state.pkg)return;state.pkg.draft=els.draft.value;resetPublishChecks('본문 변경으로 다시 확인 필요');syncProvenanceState();renderHumanAudit();savePackage();queueVersion()}
  function updateCheckProgress(){const checks=$$('input[name="publishCheck"]');const done=checks.filter(input=>input.checked).length;els.checkProgress.textContent=`${done}/${checks.length} 확인`}
  function replyBlockReason(value){if(els.commentInput.value.trim()!==state.replySource)return'원 댓글이 바뀌었어요. 답변 후보를 다시 만들어 주세요.';if(!String(value||'').trim())return'답변을 적어야 복사할 수 있어요.';if(/\[[^\]]+\]|(?:답변|상황|내용)을\s*적어(?:주세요|줘)|(?:TODO|TBD)\b/i.test(value))return'대괄호 안의 실제 답변을 채워 주세요.';return''}
  function updateReplyItem(item){const text=item.querySelector('textarea');const button=item.querySelector('button');const help=item.querySelector('.reply-help');const reason=replyBlockReason(text.value);button.setAttribute('aria-disabled',String(Boolean(reason)));item.classList.toggle('is-blocked',Boolean(reason));help.textContent=reason||'내용을 확인한 뒤 복사할 수 있어요.'}
  async function requestAiReplies(){const comment=els.commentInput.value.trim();if(!comment||!state.loggedIn||!state.csrfToken||state.replySource!==comment)return;const requestId=++state.replyRequestId;const textareas=[...els.replyList.querySelectorAll('textarea')];const snapshots=textareas.map(text=>text.value);try{const response=await fetch('/api/v1/ai/replies',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json','X-CSRF-Token':state.csrfToken},body:JSON.stringify({comment,tone:state.tone})});const payload=await response.json();if(!response.ok||!Array.isArray(payload.result)||requestId!==state.replyRequestId||els.commentInput.value.trim()!==comment)return;const current=[...els.replyList.querySelectorAll('textarea')];if(current.length!==snapshots.length||current.some((text,index)=>text.value!==snapshots[index])){setLive('내가 편집한 댓글 답변을 AI 결과보다 우선해 유지했어요.');return}payload.result.forEach((item,index)=>{const value=item.needsUserInput&&!/\[[^\]]+\]/.test(item.text)?item.text+' [직접 확인한 답변을 적어주세요]':item.text;current[index].value=value;updateReplyItem(current[index].closest('li'))});setLive('내 말투를 반영한 AI 댓글 답변 후보를 만들었어요. 미확인 사실은 직접 채워 주세요.')}catch{}}
  function refreshReplyStates(){els.replyList.querySelectorAll('li').forEach(updateReplyItem)}
  function makeReplies(){const comment=els.commentInput.value.trim();if(!comment){els.commentInput.focus();toast('답변할 댓글을 붙여넣어 주세요.');return}state.replySource=comment;const replies=Core.createReplyCandidates(comment,state.tone);els.replyList.innerHTML='';replies.forEach((reply,index)=>{const item=document.createElement('li');const text=document.createElement('textarea');text.rows=3;text.value=reply;text.setAttribute('aria-label',`${index+1}번 댓글 답변 편집`);const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent='복사';button.setAttribute('aria-label',`${index+1}번 댓글 답변 복사`);const help=document.createElement('small');help.id=`replyHelp-${index+1}`;help.className='reply-help';button.setAttribute('aria-describedby',help.id);text.addEventListener('input',()=>updateReplyItem(item));button.addEventListener('click',()=>{updateReplyItem(item);if(button.getAttribute('aria-disabled')==='true'){text.focus();toast(help.textContent);return}copyText(text.value.trim(),'댓글 답변을')});item.append(text,button,help);els.replyList.append(item);updateReplyItem(item)});els.replyArea.hidden=false;setLive('고쳐 쓸 댓글 답변 틀 세 개를 만들었어요.')}
  function resetWorkspaceInputs(){clearTimeout(state.workspaceTimer);state.workspaceTimer=null;state.topic='';state.experienceAnswers={};els.category.value='local';els.customTopic.value='';els.postType.value='visit';els.memo.value='';els.photoNotes.value='';els.relationship.value='none';renderTopics();renderInterviewFields();els.selectedTopicStatus.textContent='주제를 하나 골라주세요.';els.memoCount.textContent='0자'}
  function clearWorkspace(){const hasInput=Boolean(state.topic||els.customTopic.value.trim()||Object.keys(normalizedAnswers()).length||els.memo.value.trim()||els.photoNotes.value.trim()||els.relationship.value!=='none'||els.category.value!=='local'||els.postType.value!=='visit');if(!hasInput){toast('비울 입력 내용이 없어요.');return}if(!confirm('저장된 경험 답변과 메모를 비울까요? 말투 카드와 생성한 초안은 남아 있습니다.'))return;safeRemove(keys.workspace);resetWorkspaceInputs();markStale();els.workspaceSaveState.textContent='입력 내용을 비웠어요';setStep(1);toast('경험 입력을 비웠어요.')}
  async function clearLocalData(){if(!confirm('이 브라우저에 저장된 블로그 주소, 경험 입력, 말투 카드, 초안과 취재 사진을 모두 삭제할까요?'))return;const storageCleared=[keys.tone,keys.pkg,keys.workspace,keys.blog,keys.versions].every(safeRemove);let photosCleared=false;try{await Photos.clearPhotos();photosCleared=true;await renderPhotoVault()}catch{}state.tone=null;state.pkg=null;state.blogProfile=null;state.generatedInput='';resetWorkspaceInputs();els.blogUrl.value='';renderBlogConnection();els.toneSamples.value='';els.avoidPhrases.value='';toneInputChanged();renderTone();els.emptyResult.hidden=false;els.resultContent.hidden=true;els.resultState.textContent='경험을 기다리는 중';els.workspaceSaveState.textContent='입력하면 이 브라우저에 자동 저장돼요.';setStep(1);renderDataInventory();toast(storageCleared&&photosCleared?'이 브라우저에 저장된 데이터를 삭제했어요.':'일부 데이터를 삭제하지 못했어요. 브라우저 저장 권한을 확인해 주세요.')}
  function restoreWorkspace(){try{const raw=safeRead(keys.workspace);if(!raw)return false;const saved=JSON.parse(raw);if(saved.category&&[...els.category.options].some(option=>option.value===saved.category))els.category.value=saved.category;if(saved.postType&&[...els.postType.options].some(option=>option.value===saved.postType))els.postType.value=saved.postType;if(saved.relationship&&[...els.relationship.options].some(option=>option.value===saved.relationship))els.relationship.value=saved.relationship;state.topic=String(saved.topic||'');state.experienceAnswers=saved.experienceAnswers&&typeof saved.experienceAnswers==='object'?saved.experienceAnswers:{};els.customTopic.value=String(saved.customTopic||'');els.memo.value=String(saved.memo||'');els.photoNotes.value=String(saved.photoNotes||'');els.workspaceSaveState.textContent=`${savedTime(saved.savedAt)} 입력 복구됨`;return true}catch{safeRemove(keys.workspace);return false}}
  function restore(){restoreBlogConnection();try{const tone=safeRead(keys.tone);if(tone)state.tone=JSON.parse(tone)}catch{state.tone=null}renderTone();const restoredWorkspace=restoreWorkspace();renderTopics();renderInterviewFields(state.experienceAnswers);if(state.topic)els.selectedTopicStatus.textContent=`선택한 주제: ${state.topic}`;try{const saved=safeRead(keys.pkg);if(saved){state.pkg=JSON.parse(saved);const currentPackage=packageIsCurrent(state.pkg);state.generatedInput=currentPackage?state.pkg.sourceFingerprint||'':'';renderPackage(state.pkg,true);setStep(4);if(!currentPackage||!state.generatedInput){els.staleNotice.textContent=currentPackage?'입력 출처를 확인할 수 없는 저장 초안입니다. 다시 만들기 전에는 복사할 수 없습니다.':'이전 버전에서 만든 초안입니다. 현재 출처 기록으로 다시 만들기 전에는 복사할 수 없습니다.';els.staleNotice.hidden=false;els.resultState.textContent='다시 만들기 필요';setCopyEnabled(false)}}}catch{safeRemove(keys.pkg);state.pkg=null;state.generatedInput='';els.emptyResult.hidden=false;els.resultContent.hidden=true;els.staleNotice.hidden=true;els.resultState.textContent='경험을 기다리는 중';setCopyEnabled(false)}toneInputChanged();markStale();if(restoredWorkspace&&!state.pkg)setStep(state.topic?3:1)}
  els.connectBlog.addEventListener('click',connectBlog);els.disconnectBlog.addEventListener('click',disconnectBlog);els.naverLogin.addEventListener('click',startNaverLogin);els.naverLogout.addEventListener('click',logoutNaver);els.blogUrl.addEventListener('input',()=>els.blogUrl.removeAttribute('aria-invalid'));els.blogUrl.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();connectBlog()}});els.category.addEventListener('change',()=>{state.topic='';els.selectedTopicStatus.textContent='분야가 바뀌었어요. 새 주제를 골라주세요.';if(!Object.keys(normalizedAnswers()).length&&!els.memo.value.trim()){const defaults={local:'visit',travel:'visit',beauty:'product',parenting:'product',tech:'product',life:'howto'};els.postType.value=defaults[els.category.value]||'visit';renderInterviewFields()}renderTopics();workspaceChanged();setStep(1)});els.postType.addEventListener('change',()=>{const previous=els.postType.dataset.active||'visit';const hasAnswers=Object.keys(state.experienceAnswers).length>0;if(hasAnswers&&!confirm('글 종류를 바꾸면 지금 작성한 경험 답변을 비웁니다. 계속할까요?')){els.postType.value=previous;return}state.experienceAnswers={};renderInterviewFields();workspaceChanged();toast('글 종류에 맞는 질문으로 바꿨어요.')});els.useCustomTopic.addEventListener('click',useCustomTopic);els.customTopic.addEventListener('input',queueWorkspaceSave);els.customTopic.addEventListener('keydown',event=>{if(event.key==='Enter')useCustomTopic()});els.toneSamples.addEventListener('input',toneInputChanged);els.saveTone.addEventListener('click',saveTone);els.deleteTone.addEventListener('click',deleteTone);els.memo.addEventListener('input',workspaceChanged);els.photoNotes.addEventListener('input',workspaceChanged);els.relationship.addEventListener('change',workspaceChanged);els.generate.addEventListener('click',generate);els.applyExperience.addEventListener('click',applyExperience);els.draft.addEventListener('input',draftChanged);els.clearWorkspace.addEventListener('click',clearWorkspace);els.clearLocalData.addEventListener('click',clearLocalData);els.makeReplies.addEventListener('click',makeReplies);els.commentInput.addEventListener('input',refreshReplyStates);$$('input[name="publishCheck"]').forEach(input=>input.addEventListener('change',updateCheckProgress));els.copyTitle.addEventListener('click',()=>state.pkg&&copyControlReady(els.copyTitle)&&copyText(state.pkg.titles[0],'제목을'));els.copyBody.addEventListener('click',()=>state.pkg&&copyControlReady(els.copyBody)&&copyText(els.draft.value,'본문을'));els.copyTags.addEventListener('click',()=>state.pkg&&copyControlReady(els.copyTags)&&copyText(state.pkg.hashtags.join(' '),'해시태그를'));els.copyAll.addEventListener('click',()=>state.pkg&&copyControlReady(els.copyAll)&&copyText(Core.formatAll(state.pkg,els.draft.value),'제목·본문·태그를'));
  function titleRisk(title){return /(무조건|최고|완벽|충격|대박|TOP|베스트|절대|\d+가지)/i.test(String(title||''))?'과장·낚시 확인':''}
  function decorateTitleRisks(){els.titleCandidates.querySelectorAll('li').forEach(item=>{if(item.querySelector('.title-risk'))return;const label=titleRisk(item.querySelector('span')?.textContent);if(!label)return;const badge=document.createElement('em');badge.className='title-risk';badge.textContent=label;item.querySelector('span')?.append(badge)})}
  function enforceTrustGuard(){renderRelationshipNotice();if(!state.pkg)return;els.mobilePreview.textContent=els.draft.value;decorateTitleRisks();const audit=Core.auditHumanDraft(els.draft.value,state.pkg.topic,state.tone,{titles:state.pkg.titles,missingFields:state.pkg.missingFields,postType:state.pkg.postType});const weak=audit.issues.some(issue=>['thin-draft','missing-core'].includes(issue.code));const disclosureMissing=!Core.hasRequiredDisclosure(els.draft.value,els.relationship.value);const reasons=[];if(weak)reasons.push('검색 독자에게 줄 경험 정보가 아직 부족해요. 핵심 답변과 아쉬운 점을 보강해 주세요.');if(disclosureMissing)reasons.push('협찬·광고 고지 문구가 본문 첫 줄에 있어야 해요. 다시 만들면 자동 복구됩니다.');els.trustPanel.classList.toggle('is-blocked',Boolean(reasons.length));els.trustSummary.textContent=reasons.length?reasons.join(' '):`지어낸 사실 0개 · 내 답변 ${state.pkg.provenance?.userEvidenceCount||0}개 사용 · 복사 가능`;if(reasons.length){setCopyControl(els.copyBody,false);setCopyControl(els.copyAll,false);els.copyLockReason.textContent=reasons.join(' ')}}
  window.addEventListener('pagehide',()=>{if(state.workspaceTimer)saveWorkspace()});
  els.generate.addEventListener('click',()=>requestAnimationFrame(enforceTrustGuard));
  els.draft.addEventListener('input',enforceTrustGuard);
  els.relationship.addEventListener('change',()=>{renderRelationshipNotice();requestAnimationFrame(enforceTrustGuard)});
  els.draftVersion.addEventListener('change',()=>{els.restoreVersion.disabled=els.draftVersion.value===''});
  els.restoreVersion.addEventListener('click',restoreDraftVersion);
  els.photoFiles.addEventListener('change',addPhotoFiles);
  els.clearPhotos.addEventListener('click',async()=>{if(!confirm('이 기기의 취재 사진을 모두 삭제할까요? 되돌릴 수 없습니다.'))return;await Photos.clearPhotos();renderPhotoVault();toast('취재 사진을 모두 삭제했어요.')});
  els.refreshDataInventory.addEventListener('click',renderDataInventory);
  els.approveToneSource.addEventListener('change',toneInputChanged);
  els.toneSourceUrl.addEventListener('input',toneInputChanged);
  els.exportLocalData.addEventListener('click',exportLocalData);
  els.deleteAllLocalData.addEventListener('click',clearLocalData);
  restore();
  renderRelationshipNotice();
  enforceTrustGuard();
  renderDataInventory();
  renderVersions();
  renderPhotoVault();
})();
