'use strict';
const crypto=require('node:crypto');
function cleanKeyword(value){return typeof value==='string'?value.replace(/[<>\u0000-\u001f]/g,'').replace(/\s+/g,' ').trim().slice(0,60):''}
function isoDate(date){return date.toISOString().slice(0,10)}
function trendRange(now=new Date()){const end=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()));const start=new Date(end);start.setUTCDate(start.getUTCDate()-84);return{startDate:isoDate(start),endDate:isoDate(end),timeUnit:'week'}}
function validateTrendRequest(value){if(!value||typeof value!=='object')return{ok:false,error:'invalid_body'};const keyword=cleanKeyword(value.keyword);if(keyword.length<2)return{ok:false,error:'keyword_required'};const device=['','pc','mo'].includes(value.device||'')?value.device||'':'';return{ok:true,value:{keyword,device}}}
function createMemoryCache({ttlMs=60*60*1000,now=()=>Date.now()}={}){const values=new Map();return{get(key){const item=values.get(key);if(!item||item.expiresAt<=now()){values.delete(key);return null}return item.value},set(key,value){values.set(key,{value,expiresAt:now()+ttlMs})}}}
function createDataLabClient({clientId,clientSecret,fetchImpl=fetch,cache=createMemoryCache(),now=()=>new Date()}={}){return{async trend({keyword,device=''}){if(!clientId||!clientSecret)throw new Error('datalab_not_configured');const range=trendRange(now());const cacheKey=crypto.createHash('sha256').update(JSON.stringify({keyword,device,range})).digest('hex');const cached=cache.get(cacheKey);if(cached)return{...cached,cached:true};const request={...range,keywordGroups:[{groupName:keyword,keywords:[keyword]}]};if(device)request.device=device;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),8000);let response;try{response=await fetchImpl('https://openapi.naver.com/v1/datalab/search',{method:'POST',redirect:'error',signal:controller.signal,headers:{'X-Naver-Client-Id':clientId,'X-Naver-Client-Secret':clientSecret,'content-type':'application/json',accept:'application/json'},body:JSON.stringify(request)})}finally{clearTimeout(timer)}if(!response.ok)throw new Error('datalab_request_failed');const raw=await response.text();if(Buffer.byteLength(raw)>128000)throw new Error('datalab_response_too_large');let parsed;try{parsed=JSON.parse(raw)}catch{throw new Error('datalab_invalid_json')}const result=parsed.results?.[0];if(!result||!Array.isArray(result.data))throw new Error('datalab_schema_violation');const points=result.data.map(item=>({period:String(item.period),ratio:Number(item.ratio)})).filter(item=>/^\d{4}-\d{2}-\d{2}$/.test(item.period)&&Number.isFinite(item.ratio)&&item.ratio>=0&&item.ratio<=100).slice(-20);if(!points.length)throw new Error('datalab_schema_violation');const value={keyword,startDate:String(parsed.startDate),endDate:String(parsed.endDate),timeUnit:String(parsed.timeUnit),device:device||'all',points,metric:'relative_ratio',maximumMeaning:'선택 기간 내 최고 검색 관심도를 100으로 둔 상대값',source:'NAVER DataLab',fetchedAt:new Date().toISOString(),cached:false};cache.set(cacheKey,value);return value}}}
function searchAdSignature(timestamp,method,uri,secret){return crypto.createHmac('sha256',secret).update(`${timestamp}.${method}.${uri}`).digest('base64')}
function normalizeMonthlyCount(value){if(typeof value==='number'&&Number.isFinite(value)&&value>=0)return{display:String(Math.trunc(value)),value:Math.trunc(value),suppressed:false};const text=String(value||'').replace(/\s/g,'');if(/^<10$/.test(text))return{display:'<10',value:null,suppressed:true};if(/^\d+$/.test(text))return{display:text,value:Number(text),suppressed:false};return null}
function createSearchAdsClient({apiKey,secretKey,customerId,enabled=false,fetchImpl=fetch,cache=createMemoryCache({ttlMs:6*60*60*1000}),now=()=>Date.now()}={}){return{async keywords(keyword){if(!enabled)throw new Error('searchads_disabled');if(!apiKey||!secretKey||!customerId)throw new Error('searchads_not_configured');const clean=cleanKeyword(keyword);if(clean.length<2)throw new Error('keyword_required');const cached=cache.get(clean);if(cached)return{...cached,cached:true};const timestamp=String(now());const uri='/keywordstool';const url=new URL(`https://api.searchad.naver.com${uri}`);url.search=new URLSearchParams({hintKeywords:clean,showDetail:'1'}).toString();const response=await fetchImpl(url,{method:'GET',redirect:'error',headers:{'X-Timestamp':timestamp,'X-API-KEY':apiKey,'X-Customer':String(customerId),'X-Signature':searchAdSignature(timestamp,'GET',uri,secretKey),accept:'application/json'}});if(!response.ok)throw new Error('searchads_request_failed');const raw=await response.text();if(Buffer.byteLength(raw)>256000)throw new Error('searchads_response_too_large');let parsed;try{parsed=JSON.parse(raw)}catch{throw new Error('searchads_invalid_json')}if(!Array.isArray(parsed.keywordList))throw new Error('searchads_schema_violation');const keywords=parsed.keywordList.slice(0,20).map(item=>({keyword:cleanKeyword(item.relKeyword),monthlyPc:normalizeMonthlyCount(item.monthlyPcQcCnt),monthlyMobile:normalizeMonthlyCount(item.monthlyMobileQcCnt),competition:['낮음','중간','높음'].includes(item.compIdx)?item.compIdx:'정보 없음'})).filter(item=>item.keyword&&item.monthlyPc&&item.monthlyMobile);if(!keywords.length)throw new Error('searchads_schema_violation');const value={keywords,source:'NAVER Search Ads keyword tool',metricPeriod:'API가 제공한 월간 검색수 참고값',cpcProvided:false,cpcNotice:'이 API는 CPC를 제공하지 않습니다.',fetchedAt:new Date().toISOString(),cached:false};cache.set(clean,value);return value}}}
module.exports={cleanKeyword,trendRange,validateTrendRequest,createMemoryCache,createDataLabClient,searchAdSignature,normalizeMonthlyCount,createSearchAdsClient};
