(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.HeunjeokPhotos=api})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const TYPES=new Set(['image/jpeg','image/png','image/webp']);
function validatePhotoMeta(file){if(!file||!TYPES.has(file.type))return{ok:false,error:'지원하는 JPG·PNG·WebP 사진만 추가할 수 있어요.'};if(!Number.isFinite(file.size)||file.size<=0||file.size>15*1024*1024)return{ok:false,error:'사진 한 장은 15MB 이하여야 해요.'};return{ok:true}}
function openDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open('heunjeok-photo-vault',1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains('photos'))request.result.createObjectStore('photos',{keyPath:'id'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function sanitizePhoto(file){const valid=validatePhotoMeta(file);if(!valid.ok)throw new Error(valid.error);const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const width=Math.max(1,Math.round(bitmap.width*scale));const height=Math.max(1,Math.round(bitmap.height*scale));const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;canvas.getContext('2d',{alpha:false}).drawImage(bitmap,0,0,width,height);bitmap.close();const blob=await new Promise((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('사진을 처리하지 못했어요.')),'image/jpeg',0.82));return{blob,width,height}}
async function listPhotos(){const db=await openDb();return new Promise((resolve,reject)=>{const request=db.transaction('photos','readonly').objectStore('photos').getAll();request.onsuccess=()=>resolve(request.result.sort((a,b)=>a.createdAt.localeCompare(b.createdAt)));request.onerror=()=>reject(request.error)})}
async function addPhoto(file){const current=await listPhotos();if(current.length>=10)throw new Error('사진은 최대 10장까지 보관할 수 있어요.');const clean=await sanitizePhoto(file);const record={id:crypto.randomUUID(),fileName:String(file.name||'사진').replace(/[<>]/g,'').slice(0,120),blob:clean.blob,width:clean.width,height:clean.height,createdAt:new Date().toISOString(),note:''};const db=await openDb();await new Promise((resolve,reject)=>{const request=db.transaction('photos','readwrite').objectStore('photos').put(record);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)});return record}
async function updatePhotoNote(id,note){const db=await openDb();return new Promise((resolve,reject)=>{const store=db.transaction('photos','readwrite').objectStore('photos');const get=store.get(String(id));get.onsuccess=()=>{if(!get.result)return reject(new Error('사진을 찾을 수 없어요.'));const record={...get.result,note:String(note||'').trim().slice(0,300)};const put=store.put(record);put.onsuccess=()=>resolve(record);put.onerror=()=>reject(put.error)};get.onerror=()=>reject(get.error)})}
async function removePhoto(id){const db=await openDb();return new Promise((resolve,reject)=>{const request=db.transaction('photos','readwrite').objectStore('photos').delete(id);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)})}
async function clearPhotos(){const db=await openDb();return new Promise((resolve,reject)=>{const request=db.transaction('photos','readwrite').objectStore('photos').clear();request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)})}
return{validatePhotoMeta,sanitizePhoto,listPhotos,addPhoto,updatePhotoNote,removePhoto,clearPhotos}});
