(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.HeunjeokPlatform=api})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
  const MODES=['naver','x-article','x-thread'];
  function clean(value){return typeof value==='string'?value.replace(/\r\n?/g,'\n').trim():''}
  function sentences(text){const value=clean(text).replace(/\n+/g,' ');return value.match(/[^.!?。！？…]+(?:[.!?。！？…]+|$)/g)?.map(v=>v.trim()).filter(Boolean)||[]}
  function chunksFromParagraph(paragraph,max){const list=sentences(paragraph);const out=[];let current='';for(const sentence of list){if(sentence.length>max){if(current)out.push(current);out.push(sentence);current='';continue}const next=current?`${current} ${sentence}`:sentence;if(next.length>max){if(current)out.push(current);current=sentence}else current=next}if(current)out.push(current);return out}
  function splitThread(text,max=260){const limit=Math.max(120,Math.min(270,Number(max)||260));const paragraphs=clean(text).split(/\n\s*\n+/).map(v=>v.trim()).filter(Boolean);const raw=[];let current='';for(const paragraph of paragraphs){const next=current?`${current}\n\n${paragraph}`:paragraph;if(next.length<=limit){current=next;continue}if(current){raw.push(current);current=''}if(paragraph.length<=limit)current=paragraph;else raw.push(...chunksFromParagraph(paragraph,limit))}if(current)raw.push(current);const total=raw.length;return raw.map((value,index)=>({index:index+1,total,text:value,label:`${index+1}/${total}`,formatted:`${value}\n\n${index+1}/${total}`,overLimit:value.length>limit,limit}))}
  function hashtags(tags,max){return (Array.isArray(tags)?tags:[]).map(v=>String(v).trim()).filter(v=>/^#[0-9A-Za-z가-힣_]+$/.test(v)).slice(0,max)}
  function formatOutput({mode='naver',title='',body='',tags=[]}={}){const selected=MODES.includes(mode)?mode:'naver';const heading=clean(title);const draft=clean(body);if(selected==='x-thread')return splitThread([heading,draft].filter(Boolean).join('\n\n'));const maxTags=selected==='naver'?3:2;const suffix=hashtags(tags,maxTags).join(' ');return[heading,draft,suffix].filter(Boolean).join('\n\n')}
  function checklist(mode){if(mode==='naver')return['가격·시간·주소를 다시 확인했어요','광고·협찬 관계를 첫 화면에 표시했어요','사진 권리와 개인정보를 확인했어요','네이버 카테고리·공개 범위를 확인했어요'];return['미디어 사용 권리와 alt 텍스트를 확인했어요','광고·협찬·민감한 내용을 밝혔어요','X 커뮤니티 가이드와 공개 범위를 확인했어요','첫 문장과 스레드 순서를 직접 확인했어요']}
  function readingStats(text){const value=clean(text);const chars=value.replace(/\s/g,'').length;return{chars,minutes:chars?Math.max(1,Math.ceil(chars/500)):0,paragraphs:value?value.split(/\n\s*\n+/).length:0}}
  return{MODES,sentences,splitThread,formatOutput,checklist,readingStats};
});
