const test=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');const {validateTrendRequest,createMemoryCache,createDataLabClient,searchAdSignature,normalizeMonthlyCount,createSearchAdsClient}=require('../naver-data');
test('트렌드 요청은 짧거나 제어문자가 섞인 검색어를 정리하고 기기 필터를 제한한다',()=>{assert.equal(validateTrendRequest({keyword:'a'}).ok,false);assert.deepEqual(validateTrendRequest({keyword:'  제주<맛집>\u0000  ',device:'evil'}).value,{keyword:'제주맛집',device:''})});
test('DataLab 결과는 절대 검색량이 아닌 상대 비율과 출처·조회 시각만 반환한다',async()=>{let calls=0;const client=createDataLabClient({clientId:'id',clientSecret:'secret',fetchImpl:async(url,options)=>{calls++;assert.equal(url,'https://openapi.naver.com/v1/datalab/search');assert.equal(options.headers['X-Naver-Client-Secret'],'secret');return new Response(JSON.stringify({startDate:'2026-04-01',endDate:'2026-07-01',timeUnit:'week',results:[{data:[{period:'2026-06-24',ratio:50},{period:'2026-07-01',ratio:100}]}]}),{status:200})}});const first=await client.trend({keyword:'제주 맛집'});const second=await client.trend({keyword:'제주 맛집'});assert.equal(first.metric,'relative_ratio');assert.match(first.maximumMeaning,/상대값/);assert.equal(first.points[1].ratio,100);assert.equal(second.cached,true);assert.equal(calls,1);assert.doesNotMatch(JSON.stringify(first),/searchVolume|검색량/)});
test('캐시는 만료 뒤 값을 폐기한다',()=>{let now=0;const cache=createMemoryCache({ttlMs:10,now:()=>now});cache.set('a',{ok:true});assert.deepEqual(cache.get('a'),{ok:true});now=11;assert.equal(cache.get('a'),null)});
test('캐시는 최대 항목을 넘기지 않고 오래된 항목부터 버린다',()=>{const cache=createMemoryCache({ttlMs:1000,maxEntries:2,now:()=>0});cache.set('a',1);cache.set('b',2);cache.set('c',3);assert.equal(cache.get('a'),null);assert.equal(cache.get('b'),2);assert.equal(cache.get('c'),3)});
test('검색광고 서명은 timestamp.method.uri HMAC-SHA256 Base64 규격이다',()=>{const expected=crypto.createHmac('sha256','secret').update('123.GET./keywordstool').digest('base64');assert.equal(searchAdSignature('123','GET','/keywordstool','secret'),expected)});
test('10 미만 검색수는 임의 숫자로 바꾸지 않고 억제 상태를 보존한다',()=>{assert.deepEqual(normalizeMonthlyCount('< 10'),{display:'<10',value:null,suppressed:true});assert.deepEqual(normalizeMonthlyCount(42),{display:'42',value:42,suppressed:false});assert.equal(normalizeMonthlyCount('unknown'),null)});
test('검색광고 기능은 약관 확인 플래그가 없으면 호출하지 않는다',async()=>{let called=false;const client=createSearchAdsClient({enabled:false,apiKey:'a',secretKey:'s',customerId:'1',fetchImpl:async()=>{called=true}});await assert.rejects(()=>client.keywords('제주 맛집'),/disabled/);assert.equal(called,false)});
test('키워드 도구 결과는 검색수·경쟁만 반환하고 CPC를 만들지 않는다',async()=>{let request;const client=createSearchAdsClient({enabled:true,apiKey:'api',secretKey:'secret',customerId:'7',now:()=>123,fetchImpl:async(url,options)=>{request={url:new URL(url),options};return new Response(JSON.stringify({keywordList:[{relKeyword:'제주맛집',monthlyPcQcCnt:'< 10',monthlyMobileQcCnt:120,compIdx:'높음'}]}),{status:200})}});const result=await client.keywords('제주 맛집');assert.equal(request.url.origin,'https://api.searchad.naver.com');assert.equal(request.options.headers['X-API-KEY'],'api');assert.ok(request.options.headers['X-Signature']);assert.equal(result.keywords[0].monthlyPc.suppressed,true);assert.equal(result.cpcProvided,false);assert.match(result.cpcNotice,/제공하지 않습니다/);assert.doesNotMatch(JSON.stringify(result),/estimatedCpc|avgCpc/)});
