const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const html=fs.readFileSync('index.html','utf8'),js=fs.readFileSync('product-v2.js','utf8'),css=fs.readFileSync('product-v2.css','utf8');
let JSDOM;try{JSDOM=require('jsdom').JSDOM}catch{}
test('제품 흐름 파일을 보안 정책 안에서 로드한다',()=>{for(const file of ['backup.js','product-v2.js','product-v2.css'])assert.match(html,new RegExp(file.replace('.','\\.')));assert.doesNotMatch(js,/eval\(|new Function|document\.write/)});
test('단계형 위자드·모바일 3탭·고급 접기를 제공한다',()=>{assert.match(js,/class:'wizard-nav'/);assert.match(js,/class:'mobile-tabs'/);assert.match(js,/발행 후·참고 도구 더 보기/);assert.match(css,/grid-template-columns:repeat\(3,1fr\)/)});
test('생성 불가 사유와 필드별 5자 검증을 시각적으로 알린다',()=>{assert.match(js,/generateReason/);assert.match(js,/핵심 질문 \$\{missing\.join/);assert.match(js,/is-invalid/)});
test('생성 규칙은 핵심 3답 또는 실제 경험 메모 30자로 하나이며 상시 폴링하지 않는다',()=>{assert.match(js,/missing\.length===0\|\|memoReady/);assert.match(js,/memo\.replace\(\/\\s\/g,''\)\.length>=30/);assert.doesNotMatch(js,/setInterval\(/)});
test('보조 백업 파일이 빠져도 핵심 작성 화면 초기화를 중단하지 않는다',()=>{assert.doesNotMatch(js,/if\(!B\)return/);assert.match(js,/backup unavailable/)});
test('네이버 발행 준비만 제공하고 다른 서비스 링크는 만들지 않는다',()=>{assert.match(js,/네이버에 옮길 준비/);const external=[...js.matchAll(/https:\/\/[^'"`]+/g)].map(match=>match[0]);assert.ok(external.length>0);assert.ok(external.every(url=>url.startsWith('https://blog.naver.com/')));assert.doesNotMatch(html,/플랫폼 선택|네이버\+/)});
test('백업 가져오기와 merge·replace 선택을 제공한다',()=>{assert.match(js,/importBackup/);assert.match(js,/기존 내용 유지하고 빈 항목만 합치기/);assert.match(js,/현재 데이터를 지우고 백업으로 교체/);assert.match(js,/B\.importData/)});
test('자동 로그인·자동 발행·가짜 도달 기능을 만들지 않는다',()=>{assert.doesNotMatch(js,/fetch\([^)]*(oauth|publish)|type:'password'|function\s+autoPublish|조회수\s*예측값|도달을\s*보장/i);assert.match(js,/로그인·자동 발행·가짜 조회수/)});
test('개인정보·보안 요약 페이지도 Pages 산출물과 서버 허용 목록에 포함한다',()=>{const pages=fs.readFileSync('.github/workflows/pages.yml','utf8'),server=fs.readFileSync('server.js','utf8');for(const file of ['privacy.html','security.html']){const policy=fs.readFileSync(file,'utf8');assert.match(js,new RegExp(file.replace('.','\\.')));assert.match(pages,new RegExp(file.replace('.','\\.')));assert.match(server,new RegExp(`/${file.replace('.','\\.')}`));assert.match(policy,/script-src 'none'/);assert.match(policy,/frame-src 'none'/)}});
test('Pages 배포는 고정 의존성 설치와 전체 검사 뒤에만 시작한다',()=>{const workflow=fs.readFileSync('.github/workflows/pages.yml','utf8');assert.match(workflow,/npm ci/);assert.match(workflow,/npm run ci/);assert.match(workflow,/deploy:\n\s+needs: verify/)});

test('실제 DOM에서 데모→초안→네이버 발행 준비가 자동으로 동작한다',{skip:JSDOM?false:'jsdom 미설치'},async()=>{const dom=new JSDOM(html,{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.confirm=()=>true;w.alert=()=>{};w.open=()=>null;w.Element.prototype.scrollIntoView=()=>{};w.URL.createObjectURL=()=> 'blob:stub';w.URL.revokeObjectURL=()=>{};w.fetch=()=>Promise.reject(new Error('offline'));w.requestAnimationFrame=cb=>cb();w.localStorage.setItem('heunjeok-ui-preferences',JSON.stringify({onboarded:true}));const files=['core.js','history.js','photo-vault.js','benchmark.js','quality.js','assemble.js','postlog.js','daily.js','backup.js','app.js','benchmark-ui.js','improve-ui.js','postlog-ui.js','daily-ui.js','product-v2.js'];for(const file of files)w.eval(fs.readFileSync(file,'utf8'));const d=w.document;assert.equal(d.querySelectorAll('.wizard-nav button').length,5);assert.equal(d.querySelectorAll('.mobile-tabs button').length,3);assert.equal(d.querySelectorAll('[data-mode]').length,0);assert.match(d.querySelector('.naver-finish-panel').textContent,/네이버/);assert.equal(d.querySelector('.input-column').firstElementChild.id,'experience-tool');assert.equal(d.querySelector('.optional-tone').open,false);d.getElementById('fillDemo').click();await new Promise(resolve=>w.setTimeout(resolve,60));assert.equal(d.getElementById('generate').disabled,false);assert.equal(d.getElementById('resultContent').hidden,false);assert.equal(d.getElementById('publish-tool').hidden,false);assert.equal(d.getElementById('copyAll').textContent,'제목·본문·태그 모두 복사');dom.window.close()});
