const test=require('node:test');const assert=require('node:assert/strict');const {createAppServer,securityHeaders,createRateLimiter,validateRuntimeConfig,configuredOrigins,createAuditLogger,createOAuthStateManager,createSessionManager,sessionCookie,createNaverOAuthClient,parseCookies}=require('../server');
async function withServer(options,run){const server=createAppServer({root:process.cwd(),logger:()=>{},...options});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{await run(`http://127.0.0.1:${server.address().port}`)}finally{await new Promise(resolve=>server.close(resolve))}}
async function establish(base,origin='https://app.example'){const response=await fetch(`${base}/api/v1/session`,{headers:{origin}});const body=await response.json();return{response,body,cookie:response.headers.get('set-cookie').split(';')[0]}}
test('운영 설정은 주소의 자격 증명과 예시 비밀키를 거부한다',()=>{assert.deepEqual(validateRuntimeConfig({APP_ORIGIN:'https://example.com'}),{ok:true,errors:[]});assert.equal(validateRuntimeConfig({APP_ORIGIN:'https://user:pass@example.com'}).ok,false);assert.equal(validateRuntimeConfig({APP_ORIGIN:'https://example.com/path'}).ok,false);assert.equal(validateRuntimeConfig({APP_ORIGIN:'https://example.com',OPENAI_API_KEY:'change-me'}).ok,false)});
test('Render 주소는 APP_ORIGIN이 없을 때만 안전한 HTTPS Origin으로 사용한다',()=>{assert.deepEqual(configuredOrigins({RENDER_EXTERNAL_HOSTNAME:'heunjeok.onrender.com'}),['https://heunjeok.onrender.com']);assert.deepEqual(configuredOrigins({APP_ORIGIN:'https://custom.example',RENDER_EXTERNAL_HOSTNAME:'ignored.onrender.com'}),['https://custom.example']);assert.deepEqual(configuredOrigins({RENDER_EXTERNAL_HOSTNAME:'evil/path'}),['http://localhost:3000','http://127.0.0.1:3000'])});
test('보안 헤더는 프레임·권한·콘텐츠 추론을 차단한다',()=>{const headers=securityHeaders(true);assert.equal(headers['X-Frame-Options'],'DENY');assert.match(headers['Content-Security-Policy'],/frame-ancestors 'none'/);assert.match(headers['Permissions-Policy'],/camera=\(\)/);assert.ok(headers['Strict-Transport-Security'])});
test('정적 서버는 허용한 파일만 제공하고 경로 우회를 거부한다',()=>withServer({},async base=>{assert.equal((await fetch(`${base}/`)).status,200);assert.equal((await fetch(`${base}/server.js`)).status,404);assert.equal((await fetch(`${base}/..%2Fserver.js`)).status,404)}));
test('안내되는 기본 127.0.0.1 주소에서 세션 API를 사용할 수 있다',()=>withServer({},async base=>{const response=await fetch(`${base}/api/v1/session`);assert.equal(response.status,200);assert.match(response.headers.get('set-cookie'),/^heunjeok_session=/)}));
test('세션 쿠키는 자바스크립트 접근을 막고 운영 환경에서 Secure를 강제한다',()=>{const cookie=sessionCookie('opaque',{production:true});assert.match(cookie,/HttpOnly/);assert.match(cookie,/SameSite=Strict/);assert.match(cookie,/; Secure/);assert.match(cookie,/^__Host-/)});
test('로컬 HTTP 세션은 브라우저가 거부하는 __Host 접두어를 쓰지 않는다',()=>{const cookie=sessionCookie('opaque',{production:false});assert.match(cookie,/^heunjeok_session=/);assert.doesNotMatch(cookie,/Secure|^__Host-/)});
test('손상된 쿠키 값은 서버 예외 대신 해당 쿠키만 무시한다',()=>{assert.deepEqual(parseCookies('good=value; broken=%; another=a%20b'),{good:'value',another:'a b'})});
test('세션은 만료되고 재발급 때 이전 세션을 폐기할 수 있다',()=>{let now=100;const sessions=createSessionManager({ttlMs:10,now:()=>now});const first=sessions.create();assert.ok(sessions.get(first.id));sessions.remove(first.id);assert.equal(sessions.get(first.id),null);const second=sessions.create();now=111;assert.equal(sessions.get(second.id),null)});
test('세션·OAuth state·속도 제한 저장소는 공격 입력에도 최대 크기를 넘지 않는다',()=>{let now=0;const sessions=createSessionManager({ttlMs:100,maxEntries:2,now:()=>now});const first=sessions.create();const second=sessions.create();const third=sessions.create();assert.equal(sessions.get(first.id),null);assert.ok(sessions.get(second.id));assert.ok(sessions.get(third.id));const states=createOAuthStateManager({ttlMs:100,maxEntries:1,now:()=>now});const old=states.issue('a');const current=states.issue('b');assert.equal(states.consume('a',old),false);assert.equal(states.consume('b',current),true);const rate=createRateLimiter({limit:1,windowMs:100,maxKeys:2,now:()=>now});assert.equal(rate('a'),true);assert.equal(rate('b'),true);assert.equal(rate('c'),true);assert.equal(rate('a'),true)});
test('감사 로그는 허용한 사건과 최소 메타데이터 외 값을 버린다',()=>{const entries=[];const log=createAuditLogger(value=>entries.push(value));log({event:'oauth_started',requestId:'r1',outcome:'naver',token:'secret',body:'private'});log({event:'user_text',requestId:'r2',body:'private'});assert.equal(entries.length,1);assert.deepEqual(Object.keys(entries[0]).sort(),['at','event','outcome','requestId']);assert.doesNotMatch(JSON.stringify(entries),/secret|private/)});
test('OAuth state는 세션에 묶인 일회용 값이며 만료와 재사용을 거부한다',()=>{let now=10;const states=createOAuthStateManager({ttlMs:5,now:()=>now});const first=states.issue('session-a');assert.equal(states.consume('session-b',first),false);assert.equal(states.consume('session-a',first),false);const second=states.issue('session-a');assert.equal(states.consume('session-a',second),true);assert.equal(states.consume('session-a',second),false);const expired=states.issue('session-a');now=16;assert.equal(states.consume('session-a',expired),false)});
test('네이버 로그인 시작은 서버 설정·세션을 확인하고 공식 인증 주소만 반환한다',()=>withServer({allowedOrigins:['https://app.example'],naverClientId:'client-id',naverRedirectUri:'https://app.example/api/v1/auth/naver/callback'},async base=>{const noSession=await fetch(`${base}/api/v1/auth/naver/start`,{headers:{origin:'https://app.example'}});assert.equal(noSession.status,401);const session=await establish(base);const response=await fetch(`${base}/api/v1/auth/naver/start`,{headers:{origin:'https://app.example',cookie:session.cookie}});assert.equal(response.status,200);const body=await response.json();const url=new URL(body.authorizationUrl);assert.equal(url.origin,'https://nid.naver.com');assert.equal(url.pathname,'/oauth2.0/authorize');assert.equal(url.searchParams.get('client_id'),'client-id');assert.ok(url.searchParams.get('state').length>=32)}));
test('OAuth 클라이언트는 토큰을 서버에서만 사용하고 최소 식별값만 반환한다',async()=>{const calls=[];const fakeFetch=async(url,options)=>{calls.push({url:String(url),authorization:options.headers.authorization});return calls.length===1?new Response(JSON.stringify({access_token:'server-token',token_type:'Bearer'}),{status:200,headers:{'content-type':'application/json'}}):new Response(JSON.stringify({resultcode:'00',response:{id:'naver-user',email:'do-not-return@example.com'}}),{status:200,headers:{'content-type':'application/json'}})};const client=createNaverOAuthClient({clientId:'id',clientSecret:'secret',redirectUri:'https://app.example/callback',fetchImpl:fakeFetch});assert.equal(await client.identify('code','state'),'naver-user');assert.equal(calls[1].url,'https://openapi.naver.com/v1/nid/me');assert.equal(calls[1].authorization,'Bearer server-token')});
test('정상 콜백은 state를 소비하고 세션을 회전하며 식별 해시를 브라우저에 노출하지 않는다',()=>withServer({allowedOrigins:['https://app.example'],naverClientId:'client-id',naverRedirectUri:'https://app.example/api/v1/auth/naver/callback',identityKey:'stable-test-key',naverClient:{identify:async(code,state)=>{assert.equal(code,'one-time-code');assert.ok(state.length>=32);return'naver-user-id'}}},async base=>{const session=await establish(base);const start=await fetch(`${base}/api/v1/auth/naver/start`,{headers:{origin:'https://app.example',cookie:session.cookie}});const authorization=new URL((await start.json()).authorizationUrl);const state=authorization.searchParams.get('state');const callback=await fetch(`${base}/api/v1/auth/naver/callback?code=one-time-code&state=${encodeURIComponent(state)}`,{headers:{cookie:session.cookie},redirect:'manual'});assert.equal(callback.status,303);assert.equal(callback.headers.get('location'),'/?naverLogin=success');const rotatedCookie=callback.headers.get('set-cookie').split(';')[0];assert.notEqual(rotatedCookie,session.cookie);assert.doesNotMatch(callback.headers.get('set-cookie'),/naver-user|one-time-code/);const status=await fetch(`${base}/api/v1/auth/status`,{headers:{origin:'https://app.example',cookie:rotatedCookie}});assert.deepEqual((({loggedIn,provider})=>({loggedIn,provider}))(await status.json()),{loggedIn:true,provider:'naver'});const replay=await fetch(`${base}/api/v1/auth/naver/callback?code=one-time-code&state=${encodeURIComponent(state)}`,{headers:{cookie:session.cookie},redirect:'manual'});assert.equal(replay.status,400)}));
test('세션 삭제도 동일 출처와 CSRF를 요구하고 쿠키를 즉시 만료한다',()=>withServer({allowedOrigins:['https://app.example']},async base=>{const session=await establish(base);const rejected=await fetch(`${base}/api/v1/session`,{method:'DELETE',headers:{origin:'https://app.example',cookie:session.cookie}});assert.equal(rejected.status,403);const response=await fetch(`${base}/api/v1/session`,{method:'DELETE',headers:{origin:'https://app.example',cookie:session.cookie,'x-csrf-token':session.body.csrfToken}});assert.equal(response.status,204);assert.match(response.headers.get('set-cookie'),/Max-Age=0/)}));
test('API는 동일 출처 세션과 CSRF가 모두 있어야 하고 본문을 반사하지 않는다',()=>withServer({allowedOrigins:['https://app.example']},async base=>{const rejected=await fetch(`${base}/api/v1/security/status`,{method:'POST',headers:{origin:'https://evil.example','content-type':'application/json'},body:'{}'});assert.equal(rejected.status,403);const anonymous=await fetch(`${base}/api/v1/security/status`,{method:'POST',headers:{origin:'https://app.example','content-type':'application/json'},body:'{}'});assert.equal(anonymous.status,401);const established=await establish(base);assert.equal(established.response.status,200);const csrfRejected=await fetch(`${base}/api/v1/security/status`,{method:'POST',headers:{origin:'https://app.example','content-type':'application/json',cookie:established.cookie},body:'{}'});assert.equal(csrfRejected.status,403);const response=await fetch(`${base}/api/v1/security/status`,{method:'POST',headers:{origin:'https://app.example','content-type':'application/json',cookie:established.cookie,'x-csrf-token':established.body.csrfToken},body:JSON.stringify({secret:'do-not-reflect'})});assert.equal(response.status,200);const text=await response.text();assert.doesNotMatch(text,/do-not-reflect/);assert.match(text,/storesSecretsInBrowser/)}));
test('AI 초안 API는 네이버 로그인·CSRF·입력 검증·세션별 속도 제한을 적용한다',()=>{const sessions=createSessionManager();const issued=sessions.create();sessions.get(issued.id).auth={provider:'naver',userHash:'hash'};const draft={titles:['제목1','제목2','제목3'],paragraphs:[{text:'본문1',evidenceIds:['visit_time'],connectorOnly:false,needsCurrentCheck:false},{text:'본문2',evidenceIds:[],connectorOnly:true,needsCurrentCheck:false}],hashtags:[],photoPlan:[]};let calls=0;return withServer({allowedOrigins:['https://app.example'],sessions,aiClient:{draft:async()=>{calls++;return draft}},aiRateLimiter:createRateLimiter({limit:1,windowMs:60000})},async base=>{const headers={origin:'https://app.example','content-type':'application/json',cookie:`heunjeok_session=${issued.id}`,'x-csrf-token':issued.csrf};const payload={topic:'방문 후기',postType:'visit',memo:'직접 방문해서 기록한 충분한 메모입니다.',evidence:{visit_time:'토요일 오후 두 시'}};const response=await fetch(`${base}/api/v1/ai/draft`,{method:'POST',headers,body:JSON.stringify(payload)});assert.equal(response.status,200);assert.deepEqual((await response.json()).draft,draft);assert.equal(calls,1);const limited=await fetch(`${base}/api/v1/ai/draft`,{method:'POST',headers,body:JSON.stringify(payload)});assert.equal(limited.status,429)})});
test('AI 초안 API는 로그인하지 않은 세션의 비용 발생을 막는다',()=>withServer({allowedOrigins:['https://app.example'],aiClient:{draft:async()=>{throw new Error('must_not_call')}}},async base=>{const session=await establish(base);const response=await fetch(`${base}/api/v1/ai/draft`,{method:'POST',headers:{origin:'https://app.example','content-type':'application/json',cookie:session.cookie,'x-csrf-token':session.body.csrfToken},body:JSON.stringify({topic:'방문 후기',postType:'visit',memo:'충분한 실제 방문 메모입니다.'})});assert.equal(response.status,401);assert.match(await response.text(),/naver_login_required/)}));
test('검색광고 기능은 기본 비활성 상태를 공개하고 키워드 데이터를 노출하지 않는다',()=>withServer({allowedOrigins:['https://app.example'],searchAdsEnabled:false},async base=>{const session=await establish(base);const status=await fetch(`${base}/api/v1/naver/searchads/status`,{headers:{origin:'https://app.example',cookie:session.cookie}});assert.deepEqual((({enabled,cpcProvided})=>({enabled,cpcProvided}))(await status.json()),{enabled:false,cpcProvided:false});const response=await fetch(`${base}/api/v1/naver/searchads/keywords`,{method:'POST',headers:{origin:'https://app.example','content-type':'application/json',cookie:session.cookie,'x-csrf-token':session.body.csrfToken},body:JSON.stringify({keyword:'제주 맛집'})});assert.equal(response.status,401)}));
test('검색광고 기능은 활성화해도 로그인·CSRF를 거쳐 검증된 결과만 반환한다',()=>{const sessions=createSessionManager();const issued=sessions.create();sessions.get(issued.id).auth={provider:'naver',userHash:'hash'};let received='';const result={keywords:[{keyword:'제주맛집',monthlyPc:{display:'<10',value:null,suppressed:true},monthlyMobile:{display:'120',value:120,suppressed:false},competition:'높음'}],source:'NAVER Search Ads keyword tool',cpcProvided:false,fetchedAt:'2026-07-12T00:00:00.000Z',cached:false};return withServer({allowedOrigins:['https://app.example'],sessions,searchAdsEnabled:true,searchAdsClient:{keywords:async keyword=>{received=keyword;return result}}},async base=>{const headers={origin:'https://app.example','content-type':'application/json',cookie:`heunjeok_session=${issued.id}`,'x-csrf-token':issued.csrf};const response=await fetch(`${base}/api/v1/naver/searchads/keywords`,{method:'POST',headers,body:JSON.stringify({keyword:' 제주<맛집> '})});assert.equal(response.status,200);assert.equal(received,'제주맛집');assert.deepEqual((await response.json()).result,result)})});
test('속도 제한기는 창 안의 초과 요청을 차단한다',()=>{const rate=createRateLimiter({limit:2,windowMs:1000});assert.equal(rate('a'),true);assert.equal(rate('a'),true);assert.equal(rate('a'),false);assert.equal(rate('b'),true)});

test('클라이언트 식별은 신뢰 홉만큼 X-Forwarded-For를 오른쪽부터 사용해 스푸핑을 막는다',()=>{const {clientIdentifier}=require('../server');const req=headers=>({socket:{remoteAddress:'10.0.0.9'},headers});
  assert.equal(clientIdentifier(req({}),0),'10.0.0.9');
  assert.equal(clientIdentifier(req({'x-forwarded-for':'1.1.1.1'}),0),'10.0.0.9');
  assert.equal(clientIdentifier(req({'x-forwarded-for':'203.0.113.7'}),1),'203.0.113.7');
  assert.equal(clientIdentifier(req({'x-forwarded-for':'9.9.9.9, 203.0.113.7'}),1),'203.0.113.7');
});
test('식별 키 파생은 SESSION_SECRET을 그대로 쓰지 않고 분리 파생한다',()=>{const {deriveIdentityKey}=require('../server');const secret='x'.repeat(40);
  const derived=Buffer.from(deriveIdentityKey({},{SESSION_SECRET:secret})).toString('hex');
  assert.notEqual(derived,Buffer.from(secret).toString('hex'));
  assert.equal(Buffer.from(deriveIdentityKey({},{SESSION_SECRET:secret})).toString('hex'),derived);
  assert.equal(deriveIdentityKey({},{IDENTITY_SECRET:'sep'}),'sep');
  assert.equal(deriveIdentityKey({identityKey:'explicit'},{}),'explicit');
});
test('운영 환경은 필수 네이버 비밀값과 오리진이 없으면 기동을 거부한다',()=>{
  const base={NODE_ENV:'production',SESSION_SECRET:'s'.repeat(40),APP_ORIGIN:'https://app.example',NAVER_CLIENT_ID:'id',NAVER_CLIENT_SECRET:'secret',NAVER_REDIRECT_URI:'https://app.example/api/v1/auth/naver/callback'};
  assert.equal(validateRuntimeConfig(base).ok,true);
  assert.equal(validateRuntimeConfig({...base,NAVER_CLIENT_SECRET:''}).ok,false);
  assert.equal(validateRuntimeConfig({...base,APP_ORIGIN:''}).ok,false);
  assert.equal(validateRuntimeConfig({...base,APP_ORIGIN:'',RENDER_EXTERNAL_HOSTNAME:'heunjeok.onrender.com'}).ok,true);
});

test('AI 벤치마크 코칭은 네이버 로그인·CSRF를 요구하고 사용자 초안만으로 코칭한다',()=>{const sessions=createSessionManager();const issued=sessions.create();sessions.get(issued.id).auth={provider:'naver',userHash:'hash'};let received=null;const coachResult={overall:'구조를 조금만 손보면 좋아요.',tips:[{area:'분량',advice:'경험 장면을 하나 더 넣어보세요.'}]};return withServer({allowedOrigins:['https://app.example'],sessions,auxAiClient:{coach:async payload=>{received=payload;return coachResult}}},async base=>{
  const anon=await fetch(`${base}/api/v1/ai/benchmark`,{method:'POST',headers:{origin:'https://app.example','content-type':'application/json'},body:'{}'});assert.equal(anon.status,401);
  const headers={origin:'https://app.example','content-type':'application/json',cookie:`heunjeok_session=${issued.id}`,'x-csrf-token':issued.csrf};
  const response=await fetch(`${base}/api/v1/ai/benchmark`,{method:'POST',headers,body:JSON.stringify({draft:'충분히 긴 내 초안 본문입니다. 카페에 다녀온 기록이에요.',gaps:[{label:'분량',hint:'더 길게'}],matchScore:40,topic:'카페'})});
  assert.equal(response.status,200);assert.deepEqual((await response.json()).result,coachResult);assert.equal(received.topic,'카페');
})});
